### ISSUE TITLE
cv.Mat doesn't work

### ISSUE THREAD

**Issue by marksgy** [aoxipo/opencv.js-for-wechat-miniprogram#1]
Hi, I managed to import wasm into miniprogram, but strange things with new Mat() happens（my version of miniprogram and opencv is the newest）. Here is what i've done on opencv.js to import opencv.wasm
1. change WebAssembly to WXWebAssembly
2. change the place where Function appears (by coping your code)
3. change the place where new__ appears (by coping your code)
4. modify createWasm() because WXWebAssembly.instantiate only accept local absolute path now

After these strange things happens, the new Mat() doesn't works as it should be.
The following are the output of new Mat(600,600,cv.CV_8UC4) in chrome and in miniprogram:

![{N%LA27X{90ZE2}~3%JMOPE(1)](https://user-images.githubusercontent.com/21007696/131118434-2e2bed9c-9d9d-4ff1-b6a1-06183bdce477.png)
![_T71KJ2()F9) (L3`NN(EFX(1)](https://user-images.githubusercontent.com/21007696/131118446-8d424443-431c-4d94-b382-ce22a3337308.png)

**Comment by marksgy** [comment]
Here is my code, you can open a new miniprogram project and put the files in the /pages/index/ folder, and require the opencv.js and then init() it.

https://github.com/marksgy/miniprogram-opencv

**Comment by aoxipo** [comment]
please check the buf in wasm.js line 253
I had the same problem before, but I forgot how to solve it.
It seems your wasm can't allocate the memory.
Did you notice that overloading is invalid and can only be used with full arguments
by the way , you can use the brotli to minisize the opencv.wasm  WXWebAssembly also support load the .br file

**Comment by aoxipo** [comment]
hello，i will close this issue , if there still have any question please let me know。
